name: MonsterHamster
version: ${project.version}
main: com.gmail.nayra.MonsterHamster
authors: [ Nayra ]
description: Go hunt bosses and get rewards

commands:
  monsterhamster:
    description: Command
    aliases: [mhamster]
  monstersummon:
    description: Summon bosses
    aliases: [msummon]
  bosspoints:
    description: See your points
    aliases: [bpoints, mpoints]
  bshop:
    description: Open the shop gui
    aliases: [mshop, bosshop, bossshop, monsterhamstershop]
  menchant:
    description: Enchant weapons
    aliases: [monsterhamsterenchant, benchant]
  msetspawn:
    description: Set boss spawn
    aliases: [monsterhamstersetspawn, bossspawn, setbossspawn]
  mmodify:
    description: Modify player stats
    aliases: [pointsmodify]